# Generated by Django 6.1.1 on 2026-10-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_or_supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorsupplier',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
