# Generated by Django 6.1.1 on 2026-09-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=25)),
                ('acount', models.PositiveSmallIntegerField(default=0)),
                ('unit_cost', models.PositiveIntegerField(default=0)),
                ('supplier', models.CharField(max_length=25)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
