# Generated by Django 6.1.1 on 2026-09-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=25)),
                ('acount', models.PositiveSmallIntegerField(default=0)),
                ('unit_cost', models.PositiveIntegerField(default=0)),
                ('supplier', models.CharField(max_length=25)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Buys',
        ),
    ]
